export const CONSTANTS = {
  ROSTER_DATA_NAME: 'ROSTER_DATA_2026',
  RAW_PITCHER_STATS: 'RAW_PITCHER_STATS_2026',
  RAW_HITTER_STATS: 'RAW_HITTER_STATS_2026',
  ROSTER_STATS: 'ROSTER_STATS_2026',
  RAW_POS_STATS: 'RAW_POS_STATS_2026',
  GRAND_TOTALS_HISTORY: 'GRAND_TOTALS_HISTORY_2026',
  STALE_STATS_TIME_GAP: 20000
};